services:
  go:
    image: alpine:3.20
    container_name: go
    working_dir: /app
    command: ["/app/bin/app"]
    environment:
      PORT: ${GO_INTERNAL_PORT}
    volumes:
      - ../../sites/GO/gin:/app:ro
    networks:
      app_network:
        aliases: ["go"]
    restart: unless-stopped

networks:
  app_network:
    external: true
