services:
  go-app:
    container_name: go
    build: 
      context: ../../sites/GO/gin
      dockerfile: Dockerfile
    networks:
      - app_network
    environment:
      GO_INTERNAL_PORT: ${GO_INTERNAL_PORT}
    volumes:
      - ../../sites/GO/gin:/app

networks:
  app_network:
    external: true
