services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8015
    volumes:
      - .:/app
    ports:
      - "8015:80"
    environment:
      - DEBUG=True
    networks:
      - db_network
      - caddy_network

networks:
  db_network:
    external: true
  caddy_network:
    external: true
